
export const RECEIVE_STAGED_EMAILS = 'RECEIVE_STAGED_EMAILS';
export const SENDING_STAGED_EMAILS = 'SENDING_STAGED_EMAILS';
export const RECEIVE_EMAIL = 'RECEIVE_EMAIL';

export const REQUEST_HEADERS = 'REQUEST_HEADERS';
export const RECEIVE_HEADERS = 'RECEIVE_HEADERS';
export const TURN_ON_PROCESS_WAIT = 'TURN_ON_PROCESS_WAIT';
export const TURN_OFF_PROCESS_WAIT = 'TURN_OFF_PROCESS_WAIT';
