export const RECEIVE_STAGED_EMAILS = 'RECEIVE_STAGED_EMAILS';
export const SENDING_STAGED_EMAILS = 'SENDING_STAGED_EMAILS';
export const RECEIVE_EMAIL = 'RECEIVE_EMAIL';
export const REQUEST_MULTIPLE_EMAILS = 'REQUEST_MULTIPLE_EMAILS';
export const RECEIVE_MULTIPLE_EMAILS = 'RECEIVE_MULTIPLE_EMAILS';
export const EMAIL_SET_OFFSET = 'EMAIL_SET_OFFSET';
